import {
  Controller,
  Post,
  Headers,
  Body,
  HttpCode,
  HttpStatus,
  Req,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiHeader } from '@nestjs/swagger';
import { Request } from 'express';
import { PaymentsService } from './payments.service';

@ApiTags('Payments & Subscriptions')
@Controller('webhooks')
export class WebhooksController {
  constructor(private readonly paymentsService: PaymentsService) {}

  @Post('razorpay')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Idempotent Razorpay Webhook Handler',
    description:
      'Receives and cryptographically verifies asynchronous payment and subscription lifecycle events from Razorpay.',
  })
  @ApiHeader({
    name: 'x-razorpay-signature',
    description: 'HMAC-SHA256 signature generated by Razorpay with webhook secret',
    required: true,
  })
  @ApiResponse({
    status: 200,
    description: 'Webhook processed',
  })
  @ApiResponse({
    status: 401,
    description: 'Invalid signature',
  })
  async handleRazorpayWebhook(
    @Headers('x-razorpay-signature') signature: string,
    @Body() payload: any,
    @Req() req: Request,
  ) {
    const rawBody = (req as any).rawBody || JSON.stringify(payload);
    return this.paymentsService.processWebhook(rawBody, signature, payload);
  }
}
